import { Agent } from 'undici';
import type { IdracInfo, Sensor } from './types';
function envBool(v:string|undefined,def:boolean){if(v==null||v==='')return def; return ['1','true','yes','on'].includes(v.toLowerCase())}
function baseHost(){const h=process.env.IDRAC_HOST?.trim(); if(!h)return ''; return h.startsWith('http')?h:`https://${h}`}
function idracUrl(){return baseHost().replace(/\/+$/,'')}
function basic(){return 'Basic '+Buffer.from(`${process.env.IDRAC_USERNAME??''}:${process.env.IDRAC_PASSWORD??''}`).toString('base64')}
async function rf(path:string, timeout=Number(process.env.IDRAC_TIMEOUT_MS??6000)):Promise<any>{const ctrl=new AbortController(); const timer=setTimeout(()=>ctrl.abort(),timeout); const verify=envBool(process.env.IDRAC_VERIFY_TLS,false); try{const res=await fetch(idracUrl()+path,{headers:{Authorization:basic(),Accept:'application/json','User-Agent':'HomeLab-Dashboard/1.0'},cache:'no-store',signal:ctrl.signal,dispatcher:new Agent({connect:{rejectUnauthorized:verify}})} as RequestInit & {dispatcher:Agent}); if(!res.ok)throw new Error(`Redfish ${path} HTTP ${res.status}`); return res.json();}finally{clearTimeout(timer)}}
function arr(x:any){return Array.isArray(x?.Members)?x.Members:[]}
async function members(path:string){try{const c=await rf(path); return await Promise.all(arr(c).slice(0,64).map((m:any)=>rf(m['@odata.id']).catch((e:Error)=>({Name:m['@odata.id'],Status:{Health:'Unknown'},error:e.message}))));}catch{return []}}
function statusOf(x:any){return x?.Status?.Health || x?.Status?.State || x?.Health || 'N/A'}
function sensor(x:any):Sensor{return {name:x.Name||x.Id||x.MemberId||'N/A',status:statusOf(x),value:x.ReadingCelsius ?? x.Reading ?? x.PowerConsumedWatts ?? x.CapacityMiB ?? x.SpeedRPM ?? null,unit:x.ReadingUnits || (x.ReadingCelsius!=null?'°C':x.PowerConsumedWatts!=null?'W':x.SpeedRPM!=null?'RPM':null),reading:x.ReadingVolts ?? x.ReadingAmps ?? null}}
export async function getIdracInfo():Promise<IdracInfo>{const checkedAt=new Date().toISOString(); if(!process.env.IDRAC_HOST||!process.env.IDRAC_USERNAME||!process.env.IDRAC_PASSWORD){return {configured:false,connected:false,status:'unknown',checkedAt,idracUrl:idracUrl()||undefined,error:'Waiting for configuration'}} try{const [root,systems,managers,chassis]=await Promise.all([rf('/redfish/v1/'),members('/redfish/v1/Systems'),members('/redfish/v1/Managers'),members('/redfish/v1/Chassis')]); const sys=systems[0]||{}; const mgr=managers[0]||{}; const ch=chassis[0]||{}; const [processors,dimms,thermal,power,storageCtl,net]=await Promise.all([members(sys.Processors?.['@odata.id']||'/redfish/v1/Systems/System.Embedded.1/Processors'),members(sys.Memory?.['@odata.id']||'/redfish/v1/Systems/System.Embedded.1/Memory'),ch.Thermal?.['@odata.id']?rf(ch.Thermal['@odata.id']).catch(()=>({})):Promise.resolve({}),ch.Power?.['@odata.id']?rf(ch.Power['@odata.id']).catch(()=>({})):Promise.resolve({}),members(sys.Storage?.['@odata.id']||'/redfish/v1/Systems/System.Embedded.1/Storage'),members(sys.EthernetInterfaces?.['@odata.id']||'/redfish/v1/Systems/System.Embedded.1/EthernetInterfaces')]); const physical:any[]=[]; const virtual:any[]=[]; for(const c of storageCtl){if(c.Drives) physical.push(...await Promise.all(c.Drives.slice(0,64).map((d:any)=>rf(d['@odata.id']).catch(()=>({Name:d['@odata.id'],Status:{Health:'Unknown'}}))))); if(c.Volumes?.['@odata.id']) virtual.push(...await members(c.Volumes['@odata.id']));}
 const temps=(thermal.Temperatures||[]).map(sensor); const fans=(thermal.Fans||[]).map(sensor); const supplies=(power.PowerSupplies||[]).map(sensor); const health=statusOf(sys); return {configured:true,connected:true,status:health==='OK'?'online':health==='N/A'?'unknown':'degraded',checkedAt,lastSuccessfulCheck:checkedAt,idracUrl:idracUrl(),model:sys.Model||ch.Model||'N/A',manufacturer:sys.Manufacturer||ch.Manufacturer||'Dell',hostname:sys.HostName||mgr.HostName||'N/A',serviceTag:sys.SKU||ch.SKU||sys.SerialNumber||'N/A',serialNumber:sys.SerialNumber||ch.SerialNumber||'N/A',powerState:sys.PowerState||'N/A',health,firmwareVersion:mgr.FirmwareVersion||root.RedfishVersion||'N/A',biosVersion:sys.BiosVersion||'N/A',cpu:{summary:sys.ProcessorSummary?.Model||'N/A',count:processors.length||sys.ProcessorSummary?.Count,processors:processors.map(sensor),temperatureC:temps.find((t:Sensor)=>/cpu/i.test(t.name))?.value ?? 'N/A',utilizationPct:'N/A'},memory:{totalGiB:sys.MemorySummary?.TotalSystemMemoryGiB ?? 'N/A',usedGiB:'N/A',summary:sys.MemorySummary?.Status?.Health||'N/A',dimms:dimms.map(sensor)},temperatures:temps,fans,power:{watts:power.PowerControl?.[0]?.PowerConsumedWatts ?? 'N/A',status:statusOf(power.PowerControl?.[0]||power),supplies},storage:{controllers:storageCtl.map(sensor),virtualDisks:virtual.map(sensor),physicalDisks:physical.map(sensor),raidStatus:storageCtl.map(statusOf).find(Boolean)||'N/A'},network:net.map(sensor),rawLinks:{redfish:root['@odata.id']||'/redfish/v1/'}}}catch(e){return {configured:true,connected:false,status:'offline',checkedAt,idracUrl:idracUrl(),error:e instanceof Error?e.message:'Unable to contact the iDRAC Redfish API'}}}
